version: '3.1'
services:
  nginx:
    container_name: resume-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./www:/usr/local/apps/mysite/resume/www/
    ports:
      - 8082:80
      - 4432:443